AllCops:
  Exclude:
    - bin/**/*
    - tmp/**/*
    - vendor/**/*
    - db/migrate/**/*
    - db/schema.rb
  DisplayCopNames: true
  TargetRubyVersion: 2.3

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 16
Metrics/ClassLength:
  Max: 256
Metrics/LineLength:
  Max: 120
  Exclude:
    - spec/**/*
Metrics/MethodLength:
  Max: 15

Rails:
  Enabled: true

Style/SignalException:
  EnforcedStyle: only_raise

Style/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false
