inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/**/*
    - tmp/**/*
    - vendor/**/*
    - db/migrate/**/*
    - db/schema.rb
  DisplayCopNames: true
  TargetRubyVersion: 2.6

Documentation:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/**/*

Metrics/ClassLength:
  Max: 256

Layout/LineLength:
  Max: 120
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Max: 20
  Exclude:
    - spec/**/*

Metrics/ModuleLength:
  Max: 120

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantFreeze:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/NumericPredicate:
  EnforcedStyle: comparison
