inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/**/*
    - tmp/**/*
    - vendor/**/*
    - db/migrate/**/*
    - db/schema.rb
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 3.3

Layout/LineLength:
  Max: 150
  Exclude:
    - spec/**/*

Layout/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/**/*

Metrics/ClassLength:
  Max: 256

Metrics/MethodLength:
  Max: 20
  Exclude:
    - spec/**/*

Metrics/ModuleLength:
  Max: 256

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case
  Exclude:
    - app/models/address_parser.rb
    - app/models/net_suite_integration/*
    - app/models/reports/net_suite/*
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantFreeze:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison
