name             "stockaid"
maintainer       "Mike Virata-Stone"
maintainer_email "mike@virata-stone.com"
license          "All rights reserved"
description      "Sets up and configures StockAid"
version          "0.0.1"
