development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1

review:
  adapter: redis
  url: redis://localhost:6379/1

staging:
  adapter: redis
  url: redis://localhost:6379/1
