common: &default_settings
  license_key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>
  app_name: <%= "#{ENV['NEW_RELIC_APP_NAME']}-#{ENV['RAILS_ENV']}" %>
  log_level: info

  # To disable the agent regardless of other settings, uncomment the following:
  # agent_enabled: false

# Environment-specific settings are in this section.
# RAILS_ENV or RACK_ENV (as appropriate) is used to determine the environment.
# If your application has other named environments, configure them here.
development:
  <<: *default_settings

  # NOTE: There is substantial overhead when running in developer mode.
  # Do not use for production or load testing.
  developer_mode: true

test:
  <<: *default_settings
  # It doesn't make sense to report to New Relic from automated test runs.
  monitor_mode: false

production:
  <<: *default_settings

review:
  <<: *default_settings

staging:
  <<: *default_settings
