# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Do not keep secrets in the repository, generate them at setup and keep them in the environment.
# See lib/environment_setup.rb
default: &default
  secret_key_base: <%= ENV["STOCKAID_SECRET_KEY_BASE"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

review:
  <<: *default

staging:
  <<: *default
