# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: "Chicago" }, { name: "Copenhagen" }])
#   Mayor.create(name: "Emanuel", city: cities.first)

  category_one = Category.create({ description: "Underwear" })
  category_two = Category.create({ description: "Socks" })
  category_three = Category.create({ description: "T-Shirts" })
  category_four = Category.create({ description: "Sweatshirts/Sweaters" })
  category_five = Category.create({ description: "Pants" })
  category_six = Category.create({ description: "Flip-Flops/Slippers" })
  category_seven = Category.create({ description: "Miscellaneous" })

  item_one = Item.create({ description: "Women\'s Underwear XS - 5", category_id: category_one.id})
  item_two = Item.create({ description: "Women\'s Underwear Small - 6", category_id: category_one.id})
  item_three = Item.create({ description: "Women\'s Underwear Medium - 7", category_id: category_one.id})
  item_four = Item.create({ description: "Women\'s Underwear Large - 8", category_id: category_one.id})
  item_five = Item.create({ description: "Women\'s Underwear 1X - 9", category_id: category_one.id})
  item_six = Item.create({ description: "Women\'s Underwear 2X - 10", category_id: category_one.id})
  item_seven = Item.create({ description: "Women\'s Underwear 3X-11", category_id: category_one.id})
  item_eight = Item.create({ description: "Women\'s Underwear 4X-12", category_id: category_one.id})
  item_nine = Item.create({ description: "Women\'s Bra (S) 32", category_id: category_one.id})
  item_ten = Item.create({ description: "Women\'s Bra (M) 34", category_id: category_one.id})
  item_eleven = Item.create({ description: "Women\'s Bra (L) 36", category_id: category_one.id})
  item_twelve = Item.create({ description: "Women\'s Bra (1X) 38", category_id: category_one.id})
  item_thirteen = Item.create({ description: "Women\'s Bra (2L) 40-42", category_id: category_one.id})
  item_fourteen = Item.create({ description: "Women\'s Bra (3X) 44", category_id: category_one.id})
  item_fifteen = Item.create({ description: "Women\'s Bra (4X)", category_id: category_one.id})
  item_sixteen = Item.create({ description: "Girl\'s Panties – (2-3)", category_id: category_one.id})
  item_seventeen = Item.create({ description: "Girl\'s Panties – (4-5)", category_id: category_one.id})
  item_eighteen = Item.create({ description: "Girl\'s Panties – (6)", category_id: category_one.id})
  item_nineteen = Item.create({ description: "Girl\'s Panties – (7-8)", category_id: category_one.id})
  item_twenty = Item.create({ description: "Girl\'s Panties – (10-12)", category_id: category_one.id})
  item_twenty_one = Item.create({ description: "Girl\'s Panties – (14)", category_id: category_one.id})
  item_twenty_two = Item.create({ description: "Girl\'s Panties – (16)", category_id: category_one.id})
  item_twenty_three = Item.create({ description: "Men\'s Brief/Boxers – XS(28-30)", category_id: category_one.id})
  item_twenty_four = Item.create({ description: "Men\'s Brief/Boxers- S (32-33)", category_id: category_one.id})
  item_twenty_five = Item.create({ description: "Men\'s Brief/Boxers – M (34-36)", category_id: category_one.id})
  item_twenty_six = Item.create({ description: "Men\'s Brief/Boxers - L (38-40)", category_id: category_one.id})
  item_twenty_seven = Item.create({ description: "Men\'s Brief/Boxers – 1X (40-42)", category_id: category_one.id})
  item_twenty_eight = Item.create({ description: "Underwear-boys-(2-3T)", category_id: category_one.id})
  item_twenty_nine = Item.create({ description: "Underwear-boys-XS/4-5", category_id: category_one.id})
  item_thirty = Item.create({ description: "Underwear-boys-Small", category_id: category_one.id})
  item_thirty_one = Item.create({ description: "Underwear-boys-Med.", category_id: category_one.id})
  item_thirty_two = Item.create({ description: "Underwear-boys-Large", category_id: category_one.id})
  item_thirty_three = Item.create({ description: "Underwear-boys-XLarge", category_id: category_one.id})
  item_thirty_four = Item.create({ description: "Underwear-boys-XLarge", category_id: category_two.id})

  Inventory.create({ current_quantity: 10, item_id: item_one.id })
  Inventory.create({ current_quantity: 20, item_id: item_two.id })

